export enum CodeUser{
    CONTRACTOR = 'CTA',
    RECRUITER = 'CTL',
    ADMIN = 'ADM',
    PLANEACION = 'PLNC',
    NOMINA = 'NMA',
    JURIDICO = 'JURD',
    SUPERVISOR = 'SPV',
    DESACTIVADO = 'DTV',
    SUPERVISORAREAC= 'SPVAC',
    SUPERVISORAREAN = 'SPVAN',
}