import { DecimalPipe } from "@angular/common";

export interface IContractor{
    id?: any;
    consecutivo: string;
    cpc: string;
    nombreCpc: string;
    contrato: string;
    compromiso: string;
    fechaContrato: Date;
    fechaInicioProyectado: Date;
    fechaInicioReal: Date;
    fechaFinalizacion: string;
    honorariosMensuales: string;
    actividad: string;
    encabezado: string;
    ejecucion: string;
    obligacionesGenerales: string;
    obligacionesEspecificas: string;
    profesional: string;
    laboral: string;
    fechaComite: Date;
    requierePoliza: string;
    noPoliza: string;
    vigenciaInicial: Date;
    vigenciaFinal: Date;
    fechaExPedicionPoliza: Date;
    valorAsegurado: DecimalPipe;
    fechaExaPreocupacional: Date;
    nivel: string;
    interventor: string;
    cargoInterventor: string;
    noAdicion: string;
    fechaInicioAplicacion: Date;
    fechaterminacionAplicacion: Date;
    duracionTotal: number;
    eps: string;
    pension: string;
    arl: string;
    cuentabancaria: string;
    tipodecuenta: string;
    entidadcuentabancaria: string;
}