export interface ContractorPersonalInformation{
    nombre: string;
    apellido: string;
    identificacion: string;
    lugarExpedicion: string;
    totalValue: string;
    tecnico: string;
    tecnologo: string;
    pregrado: string;
    especializacion: string;
    maestria: string;
    doctorado: string;
    genero: string;
    fechaNacimiento: Date;
    nacionalidad: string;
    direccion: string;
    departamento: string;
    municipio: string;
    barrio: string;
    telefono: string;
    celular: string;
    correo: string;
    tipoAdministradora: string;
    administradora: string;
    cuentaBancaria: string;
    tipoCuenta: string;
    entidadCuentaBancaria: string;
    fechaActualizacion: string;
}